export const INVALIDATE_PARAM = 'INVALIDATE_PARAM';
export const UPDATE_PARAM = 'UPDATE_PARAM';
export const REQUEST_DATA = 'REQUEST_DATA';
export const SET_RESULT = 'SET_RESULT';
export const INSERT_PANEL = 'INSERT_PANEL';
export const DELETE_PANEL = 'DELETE_PANEL';
export const QUERY_TO_PARAMS = 'QUERY_TO_PARAMS';
export const UPDATE_URL = 'UPDATE_URL';
export const REQUEST_GEOMDATA = 'REQUEST_GEOMDATA';
export const SET_GEOJSON = 'SET_GEOJSON';

