export const SET_PARAMS = 'SET_PARAMS';
export const SET_PRODUCT = 'SET_PRODUCT';
export const SET_RESULT = 'SET_RESULT';
export const INSERT_PANEL = 'INSERT_PANEL';
export const DELETE_PANEL = 'DELETE_PANEL';
export const RECONCILE_PARAMS = 'RECONCILE_PARAMS';
export const REQUEST_GEOMDATA = 'REQUEST_GEOMDATA';
export const SET_GEOJSON = 'SET_GEOJSON';
